### ISSUE TITLE
Handle status code responses for delete_all_rules (file_path: src/twitter_client.py)

### ISSUE THREAD

**Issue by k-styles** [k-styles/Twitter-SOS-Client#6]
Write code to handle status codes except 200 and show error messages/warnings received from Twitter API in a readable form. Preferably use a different Twitter account than the one working on the add_rules function.

**Comment by misterpalindrome** [comment]
Added del_all_rules argument to app.py
Error messages for delete_all_rules in twitter_client.py
Corrected the connection for above two.
